services:
  - type: web
    name: cabzee-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node --max-old-space-size=300 server.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: NODE_OPTIONS
        value: --max-old-space-size=300
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 5000
